export const SIGNIN_ROUTE = "/sign-in"
export const PANEL_ROUTE = "/panel/"
export const CREATE_BOOK_ROUTE = "/create-book"
export const CHANGE_BOOK_ROUTE = "/change-book/"
export const ORDER_ROUTE = "/order/"